### ISSUE TITLE
[ConfigChecker] Checking passes on wrong port number and wrong hostnames

### ISSUE THREAD

**Issue by oaizab** [oaizab/Webserv#2]
https://github.com/oaizab/Webserv/blob/3d94a6878bea7498c6bbcf1aad59abc5cf007f14/src/ConfigChecker.cpp#L291

tests used
 - listen 0dede:8044
 - listen 74384387437

**Comment by Archer-01** [comment]
My bad. When the `listen` directive has one argument without a colon ":", it checks for IP address or host only.
And I didn't know that NGINX tests if the hostname is valid or not.

**Comment by Archer-01** [comment]
There's one more thing. It's not that hostnames cannot begin with digits, they can. It's just that NGINX tests that if that hostname really exists. Let's take the hostname "42localhost' for example.
You can just add it to "/etc/hosts" and it will work on NGINX.
